"""make it work

Revision ID: e2bfc1dda4bc
Revises: be3f72f81f03
Create Date: 2024-01-26 12:00:20.204638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2bfc1dda4bc'
down_revision = 'be3f72f81f03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
